//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MULE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follower
    {
        public int follower_id { get; set; }
        public int brower_user_id { get; set; }
        public int creator_user_id { get; set; }
    }
}
